const categories = {
  STEAK : "steak",
  SPAGHETTI : "spaghetti",
  SNACK : "snack",
  SALAD : "salad",
  DRINKS : "drinks",
}

export const allMenus = [
  {
    _id : "stk-tds",
    name: "Tenderloin Steak",
    category: categories.STEAK,
    desc: "Whole Smoked Beef Tenderloin with Lemon Horseradish Cream",
    longDesc:
      "Rib-eye steaks, one of the most common and best types of steak, come from the beef rib primal cut; the corresponding roast is the prime rib. Rib-eye steaks, sometimes called beauty steaks, are tender, juicy and very flavorful, with just the right amount of fat...",
    rating: 4,
    price: 500,
    img: "/assets/menus/steaks/tenderloin-steak.png",
  },
  {
    _id : "stk-bcs",
    name: "Beef Cowboy Steak",
    category: categories.STEAK,
    desc: "Cowboy Steak With Grilled Red Onion Salad",
    rating: 4,
    price: 1000,
    img: "/assets/menus/steaks/beef-cowboy-steak.png",
  },
  {
    _id : "stk-brs",
    name: "Boneless Ribeye Steak",
    category: categories.STEAK,
    desc: "Marinated Rib Eye with Salad",
    rating: 5,
    price: 1200,
    img: "/assets/menus/steaks/boneless-ribeye-steak.png",
  },
  {
    _id : "stk-prs",
    name: "Prime Ribeye Steaks",
    category: categories.STEAK,
    desc: "Pri1me Ribeye grilled with seasoning sauce",
    rating: 5,
    price: 1500,
    img: "/assets/menus/steaks/prime-ribeye-steak.png",
  },
  {
    _id : "stk-tbs",
    name: "TBone Steak",
    category: categories.STEAK,
    desc: "A minced garlic clove, crushed red pepper",
    rating: 3,
    price: 700,
    img: "/assets/menus/steaks/tbone-steak.png",
  },

  {
    _id : "spg-fc",
    name: "Fettuccine Carbonara",
    category: categories.SPAGHETTI,
    desc: "Creamy Sauce with Shrimp and Fettuccine",
    rating: 5,
    price: 60,
    img: "/assets/menus/spaghetti/fettuccine-carbonara.png",
  },
  {
    _id : "spg-cfa",
    name: "Chicken Fettuccine Carbonara",
    category: categories.SPAGHETTI,
    desc: "Creamy sauce and Loaded with chicken breast",
    rating: 4,
    price: 65,
    img: "/assets/menus/spaghetti/chicken-fettuccine-carbonara.png",
  },
  {
    _id : "spg-sao",
    name: "Shrimp Aglio e Olio",
    category: categories.SPAGHETTI,
    desc: "Spaghetti with garlic, olive oil and Shrimp",
    rating: 3,
    price: 50,
    img: "/assets/menus/spaghetti/shrimp-aglio-e-olio.png",
  },
  {
    _id : "spg-sb",
    name: "Spaghetti Bolognese",
    category: categories.SPAGHETTI,
    desc: "Spaghetti sautéed with minced beef and bolognese sauce",
    rating: 4,
    price: 50,
    img: "/assets/menus/spaghetti/spaghetti-bolognese.png",
  },
  {
    _id : "spg-cts",
    name: "Creamy Tomato Spaghetti",
    category: categories.SPAGHETTI,
    desc: "Spaghetti with creamy tomato sauce, Kid friendly and Vegetarian",
    rating: 3,
    price: 40,
    img: "/assets/menus/spaghetti/creamy-tomato-spaghetti.png",
  },
  {
    _id : "spg-vs",
    name: "Vegetarian Spaghetti",
    category: categories.SPAGHETTI,
    desc: "Spaghetti with onion, zucchini, peppers, mushrooms and paprika",
    rating: 4,
    price: 35,
    img: "/assets/menus/spaghetti/vegetarian-spaghetti.png",
  },
  {
    _id : "spg-vc",
    name: "Vegetarian Carbonara",
    category: categories.SPAGHETTI,
    desc: "Spaghetti with onion, garlic, olive oil, mushrooms and creamy sauce ",
    rating: 4,
    price: 35,
    img: "/assets/menus/spaghetti/vegetarian-carbonara.png",
  },

  {
    _id : "snk-fm",
    name: "Fried Mozzarella",
    category: categories.SNACK,
    desc: "Fried Mozarella Cheese and Tomato Sauce",
    rating: 4,
    price: 40,
    img: "/assets/menus/snacks/fried-mozzarella.png",
  },
  {
    _id : "snk-gf",
    name: "Gnocco Fritto",
    category: categories.SNACK,
    desc: "Square pieces of leavened, lard-enriched dough fried in",
    rating: 4,
    price: 65,
    img: "/assets/menus/snacks/gnocco-fritto.png",
  },
  {
    _id : "snk-ff",
    name: "French Fries",
    category: categories.SNACK,
    desc: "Fry Potatoes with Tomato sauce",
    rating: 5,
    price: 30,
    img: "/assets/menus/snacks/french-fries.png",
  },

  {
    _id : "sld-s",
    name: "Salad",
    category: categories.SALAD,
    desc: "Onion, cucumber, carrot, green apple, tomatoes, olive oil and lemon",
    rating: 4,
    price: 30,
    img: "/assets/menus/salads/salad.png",
  },
  {
    _id : "sld-fs",
    name: "Fruit Salad",
    category: categories.SALAD,
    desc: "Mixed Fruits with mayo sauce",
    rating: 5,
    price: 35,
    img: "/assets/menus/salads/fruit-salad.png",
  },
  {
    _id : "sld-cs",
    name: "Chicken Salad",
    category: categories.SALAD,
    desc: "Grilled Chicken with Mixed Vegetables",
    rating: 5,
    price: 50,
    img: "/assets/menus/salads/chicken-salad.png",
  },

  {
    _id : "drn-l",
    name: "Lemonade",
    category: categories.DRINKS,
    desc: "Fresh lemon with squashed water",
    rating: 4,
    price: 20,
    img: "/assets/menus/drinks/lemonade.png",
  },
  {
    _id : "drn-sc",
    name: "Strawberry Cocktail",
    category: categories.DRINKS,
    desc: "Strawberry Gin Smas with Fresh Strawberries and Vodka",
    rating: 5,
    price: 30,
    img: "/assets/menus/drinks/strawberry-cocktail.png",
  },
];

export const reviews = [
  {
    name: "Richard Hanitio",
    position: "CEO of Google",
    img: "/assets/richardhanitio.png",
    comment:
      "Bienvenue is the best Italian restaurant in the world. The food made by world class chef, the place is aesthetic, everything is just perfect.",
  },
  {
    name: "Ricky",
    position: "CEO of UPH",
    img: "/assets/ricky.png",
    comment:
      "Everything we ate was fresh and delicious. The award-winning chefs use the best quality ingredients to produce dishes that are simply delightful.",
  },
  {
    name: "Calvin Wendy",
    position: "CEO of Tesla",
    img: "/assets/calvinwendy.png",
    comment:
      "Bienvenue is one of the best Italian restaurant in the world. The food is really awesome and the place also awesome.",
  },
  {
    name: "Jay Park",
    position: "CEO of Hybe",
    img: "/assets/jaypark.png",
    comment:
      "This place is great! They know what they’re doing and serve well.",
  },
];